name: Nginx Proxy Manager
run-name: Debian Linux Matrix Build 🚀
on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]
jobs:
    debian-versions:
      runs-on: ubuntu-latest
      continue-on-error: true
      container:
        image: debian:12-slim
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            path: main
        - name: Test action output
          run: |
            printf (dpkg --print-architecture)
            printf $(awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release)
            printf $(awk -F'=' '/^VERSION_ID=/{ print $NF }' /etc/os-release)
          shell: bash