name: Nginx Proxy Manager
run-name: Debian Linux Matrix Build 🚀
on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]
jobs:
    debian-versions:
      runs-on: ubuntu-latest
      continue-on-error: true
      strategy:
        matrix:
          debian: ['debian:10-slim', 'debian:11-slim', 'debian:12-slim']
      container:
        image: ${{ matrix.debian }}
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            path: main
        - name: Test action output
          run: |
            printf $(awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release)
          shell: bash